DROP TABLE MYLIBRARY
CASCADE CONSTRAINTS;

CREATE TABLE MYLIBRARY (
	WISHSEQ NUMBER CONSTRAINT PK_WISH_01 PRIMARY KEY,,
    MEMBERNUM NUMBER,
    CONSTRAINT FK_MYOFFICE_01 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM),
    WISHBOOK NUMBER,
    CONSTRAINT FK_MYOFFICE_02 FOREIGN KEY(WISHBOOK) 
    REFERENCES BOOK(BOOKNUM)
);


CREATE SEQUENCE SEQ_WISH
START WITH 1
INCREMENT BY 1;


SELECT * FROM MYLIBRARY
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10000);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 101, 10001);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10002);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10003);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10004);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10005);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10006);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10007);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10008);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10009);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10010);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10011);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10012);
INSERT INTO MYLIBRARY(WISHSEQ, MEMBERNUM, WISHBOOK)
VALUES(SEQ_WISH.NEXTVAL, 100, 10013);



 SELECT BOOKNUM, BOOKTITLE, CATEGORIES, BOOKREADCOUNT, BOOKDEL, GRADE, AUTHOR, ISSUEDATE, BOOKHEADER, PUBLISHER, RNUM 
 FROM (SELECT ROW_NUMBER()OVER(ORDER BY REVSEQ DESC) AS RNUM, BO.BOOKNUM, BOOKTITLE, CATEGORIES, BOOKREADCOUNT, BOOKDEL, GRADE, AUTHOR, ISSUEDATE, BOOKHEADER, PUBLISHER 
	   FROM REVIEW RE, BOOK BO 
    	 WHERE RE.BOOKNUM = BO.BOOKNUM
	     AND RE.MEMBERNUM = 100)       
	      WHERE RNUM >= 1 AND RNUM <= 3
